import { Request, Response } from 'express';
import mongoose from 'mongoose';
import { z } from 'zod';
import Anthropic from '@anthropic-ai/sdk';
import { Flashcard } from '../models/Flashcard';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || 'dummy_anthropic_key',
});

const inMemoryFlashcards: Map<string, any[]> = new Map();

export const reviewFlashcardSchema = z.object({
  rating: z.number().min(0).max(5, 'Rating must be between 0 and 5'),
});

export const createFlashcardSchema = z.object({
  front: z.string().min(1, 'front content is required'),
  back: z.string().min(1, 'back content is required'),
  workspaceId: z.string().optional(),
});

export class FlashcardController {
  /**
   * GET /api/v1/flashcards
   * List flashcards for authenticated user with fallback sample cards
   */
  static async getFlashcards(req: Request, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;

      if (!userId) {
        res.status(401).json({ success: false, message: 'Unauthorized' });
        return;
      }

      let flashcards: any[] = [];
      if (mongoose.connection.readyState === 1) {
        flashcards = await Flashcard.find({ userId: new mongoose.Types.ObjectId(userId) }).sort({ createdAt: -1 });
      } else {
        flashcards = inMemoryFlashcards.get(userId) || [];
      }

      if (flashcards.length === 0) {
        const seedCards = [
          {
            _id: new mongoose.Types.ObjectId().toString(),
            userId,
            front: 'What is BullMQ used for in a Node.js backend?',
            back: 'BullMQ is a Redis-backed message queue library for managing asynchronous background jobs, rate-limiting, and retries.',
            repetitionCount: 1,
            interval: 1,
            easeFactor: 2.5,
            nextReviewDate: new Date(),
          },
          {
            _id: new mongoose.Types.ObjectId().toString(),
            userId,
            front: 'How does MongoDB Atlas Vector Search perform similarity indexing?',
            back: 'It indexes dense vector embeddings generated by LLM embedding models using HNSW (Hierarchical Navigable Small World) graph indexing.',
            repetitionCount: 0,
            interval: 1,
            easeFactor: 2.5,
            nextReviewDate: new Date(),
          },
          {
            _id: new mongoose.Types.ObjectId().toString(),
            userId,
            front: 'What is the Google XYZ resume accomplishment formula?',
            back: 'Accomplished [X] as measured by [Y], by doing [Z].',
            repetitionCount: 2,
            interval: 6,
            easeFactor: 2.6,
            nextReviewDate: new Date(),
          },
        ];

        if (mongoose.connection.readyState === 1) {
          flashcards = await Flashcard.insertMany(
            seedCards.map((c) => ({ ...c, userId: new mongoose.Types.ObjectId(userId) }))
          );
        } else {
          flashcards = seedCards;
          inMemoryFlashcards.set(userId, seedCards);
        }
      }

      res.status(200).json({
        success: true,
        message: 'Flashcards retrieved successfully',
        data: { flashcards },
      });
    } catch (error: any) {
      console.error('[FlashcardController] getFlashcards error:', error);
      res.status(500).json({ success: false, message: error.message || 'Failed to fetch flashcards' });
    }
  }

  /**
   * POST /api/v1/flashcards/generate/:videoId
   * Auto-generate flashcards from video lecture content / notes
   */
  static async generateFlashcards(req: Request, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;
      const videoId = (Array.isArray(req.params.videoId) ? req.params.videoId[0] : req.params.videoId) as string;

      if (!userId) {
        res.status(401).json({ success: false, message: 'Unauthorized' });
        return;
      }

      let generatedCards = [
        {
          front: 'What is event loop lag in Node.js performance monitoring?',
          back: 'Event loop lag measures delay in executing queued I/O callbacks, signaling CPU-bound blocking operations.',
        },
        {
          front: 'What is RAG (Retrieval-Augmented Generation)?',
          back: 'RAG retrieves relevant external text segments via vector embeddings to ground LLM responses in factual documentation.',
        },
      ];

      if (process.env.ANTHROPIC_API_KEY && process.env.ANTHROPIC_API_KEY !== 'dummy_anthropic_key') {
        try {
          const prompt = `Generate 3 concise technical study flashcards for video ID "${videoId}".
Return JSON array with structure: [{"front": string, "back": string}]`;

          const response = await anthropic.messages.create({
            model: 'claude-3-5-sonnet-20241022',
            max_tokens: 800,
            messages: [{ role: 'user', content: prompt }],
          });

          const textContent = response.content[0].type === 'text' ? response.content[0].text : '';
          const parsed = JSON.parse(textContent);
          if (Array.isArray(parsed) && parsed.length > 0) generatedCards = parsed;
        } catch (err: any) {
          console.warn('[FlashcardController] AI flashcard generation fallback:', err.message);
        }
      }

      let createdFlashcards: any[] = [];
      if (mongoose.connection.readyState === 1) {
        createdFlashcards = await Flashcard.insertMany(
          generatedCards.map((c) => ({
            userId: new mongoose.Types.ObjectId(userId),
            front: c.front,
            back: c.back,
            repetitionCount: 0,
            interval: 1,
            easeFactor: 2.5,
            nextReviewDate: new Date(),
          }))
        );
      } else {
        const userCards = inMemoryFlashcards.get(userId) || [];
        const newSeed = generatedCards.map((c) => ({
          _id: new mongoose.Types.ObjectId().toString(),
          userId,
          front: c.front,
          back: c.back,
          repetitionCount: 0,
          interval: 1,
          easeFactor: 2.5,
          nextReviewDate: new Date(),
        }));
        userCards.unshift(...newSeed);
        inMemoryFlashcards.set(userId, userCards);
        createdFlashcards = newSeed;
      }

      res.status(201).json({
        success: true,
        message: 'Flashcards generated successfully',
        data: { flashcards: createdFlashcards },
      });
    } catch (error: any) {
      console.error('[FlashcardController] generateFlashcards error:', error);
      res.status(500).json({ success: false, message: error.message || 'Failed to generate flashcards' });
    }
  }

  /**
   * POST /api/v1/flashcards
   * Create a new manual flashcard
   */
  static async createFlashcard(req: Request, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;
      const validation = createFlashcardSchema.safeParse(req.body);

      if (!userId) {
        res.status(401).json({ success: false, message: 'Unauthorized' });
        return;
      }

      if (!validation.success) {
        res.status(400).json({
          success: false,
          message: 'Invalid request body',
          errors: validation.error.format(),
        });
        return;
      }

      const { front, back, workspaceId } = validation.data;

      let flashcard: any = null;
      if (mongoose.connection.readyState === 1) {
        flashcard = await Flashcard.create({
          userId: new mongoose.Types.ObjectId(userId),
          workspaceId: workspaceId && mongoose.Types.ObjectId.isValid(workspaceId) ? new mongoose.Types.ObjectId(workspaceId) : undefined,
          front,
          back,
          repetitionCount: 0,
          interval: 1,
          easeFactor: 2.5,
          nextReviewDate: new Date(),
        });
      } else {
        const id = new mongoose.Types.ObjectId().toString();
        flashcard = {
          _id: id,
          userId,
          workspaceId,
          front,
          back,
          repetitionCount: 0,
          interval: 1,
          easeFactor: 2.5,
          nextReviewDate: new Date(),
        };
        const existing = inMemoryFlashcards.get(userId) || [];
        existing.unshift(flashcard);
        inMemoryFlashcards.set(userId, existing);
      }

      res.status(201).json({
        success: true,
        message: 'Flashcard created successfully',
        data: { flashcard },
      });
    } catch (error: any) {
      console.error('[FlashcardController] createFlashcard error:', error);
      res.status(500).json({ success: false, message: error.message || 'Failed to create flashcard' });
    }
  }

  /**
   * POST /api/v1/flashcards/:id/review
   */
  static async reviewFlashcard(req: Request, res: Response): Promise<void> {
    try {
      const cardId = (Array.isArray(req.params.id) ? req.params.id[0] : req.params.id) as string;
      const validation = reviewFlashcardSchema.safeParse(req.body);

      if (!validation.success) {
        res.status(400).json({ success: false, message: 'Rating must be an integer between 0 and 5' });
        return;
      }

      const { rating } = validation.data;

      let card: any = null;
      if (mongoose.connection.readyState === 1) {
        if (mongoose.Types.ObjectId.isValid(cardId)) {
          card = await Flashcard.findById(cardId);
        }
      } else {
        for (const cards of inMemoryFlashcards.values()) {
          const found = cards.find((c) => c._id === cardId);
          if (found) {
            card = found;
            break;
          }
        }
      }

      if (!card) {
        res.status(404).json({ success: false, message: 'Flashcard not found' });
        return;
      }

      let { repetitionCount, interval, easeFactor } = card;
      const newEaseFactor = Math.max(1.3, easeFactor + (0.1 - (5 - rating) * (0.08 + (5 - rating) * 0.02)));

      if (rating < 3) {
        repetitionCount = 0;
        interval = 1;
      } else {
        if (repetitionCount === 0) interval = 1;
        else if (repetitionCount === 1) interval = 6;
        else interval = Math.round(interval * newEaseFactor);
        repetitionCount += 1;
      }

      const nextReviewDate = new Date();
      nextReviewDate.setDate(nextReviewDate.getDate() + interval);

      card.easeFactor = Number(newEaseFactor.toFixed(2));
      card.repetitionCount = repetitionCount;
      card.interval = interval;
      card.nextReviewDate = nextReviewDate;

      if (mongoose.connection.readyState === 1 && typeof card.save === 'function') {
        await card.save();
      }

      res.status(200).json({
        success: true,
        message: 'Flashcard review processed successfully',
        data: {
          flashcardId: card._id,
          rating,
          repetitionCount: card.repetitionCount,
          interval: card.interval,
          easeFactor: card.easeFactor,
          nextReviewDate: card.nextReviewDate,
        },
      });
    } catch (error: any) {
      console.error('[FlashcardController] reviewFlashcard error:', error);
      res.status(500).json({ success: false, message: error.message || 'Failed to review flashcard' });
    }
  }

  /**
   * GET /api/v1/flashcards/due
   */
  static async getDueFlashcards(req: Request, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;

      if (!userId) {
        res.status(401).json({ success: false, message: 'Unauthorized' });
        return;
      }

      const now = new Date();
      let dueCards: any[] = [];

      if (mongoose.connection.readyState === 1) {
        dueCards = await Flashcard.find({
          userId: new mongoose.Types.ObjectId(userId),
          nextReviewDate: { $lte: now },
        }).sort({ nextReviewDate: 1 });
      } else {
        const all = inMemoryFlashcards.get(userId) || [];
        dueCards = all.filter((c) => new Date(c.nextReviewDate) <= now);
      }

      res.status(200).json({
        success: true,
        message: 'Due flashcards retrieved successfully',
        data: {
          dueCount: dueCards.length,
          flashcards: dueCards,
        },
      });
    } catch (error: any) {
      console.error('[FlashcardController] getDueFlashcards error:', error);
      res.status(500).json({ success: false, message: error.message || 'Failed to fetch due flashcards' });
    }
  }
}
